name: SampleWebApptest CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Login 
        uses: Azure/testcregistry
        with:
        # Container registry server url
        login-server: testcregistry.azurecr.io
        # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }} 
    
    - name: Build and Push the Docker image
      run:  | 
       docker build ./SampleWebApplication -t testcregistry.azurecr.io/samplewebapptest:${{ github.run_id }}
       docker push testcregistry.azurecr.io/samplewebapptest:${{ github.run_id }} 
